version: '3.0'

services:
  web:
    image: rails_api_base
    build: .
    command: rm -f tmp/pids/server.pid &&  bundle exec rails s -b 0.0.0.0 -p 3000
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - gems:/gems:z
    links:
      - "db:db"
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db_data:
  gems:
